# PANDAS AND NUMPY

## 1. PANDAS 
Pandas is the industry-standard Python library used for data manipulation, analysis, and cleaning.

<b>DataFrame</b>

In [13]:
import pandas as pd
data = {'Name': ['John','peter','sakshi'],
       'Age': [25,30,35],
       'City': ['Chennai','Delhi','Pune']}
df = pd.DataFrame(data)
print(df)

     Name  Age     City
0    John   25  Chennai
1   peter   30    Delhi
2  sakshi   35     Pune

In [42]:
import pandas as pd
data2 = {'Name': ["John","peter","sakshi"],
       'Age': [25,30,35],
       'City': ['Chennai','Delhi','Pune']}
df2 = pd.DataFrame(data2)
print(df)

     Name  Age     City
0    John   25  Chennai
1   peter   30    Delhi
2  sakshi   35     Pune

<b>Creating a Series </b>

In [43]:
ages = pd.Series([25,35,30], name = 'age')
print (type(ages))
print (ages)

<class 'pandas.Series'>
0    25
1    35
2    30
Name: age, dtype: int64

In [44]:
df['Age']>25

0    False
1     True
2     True
Name: Age, dtype: bool

<b>Filtering</b>

In [45]:
df[df['Age']>25]

     Name  Age   City
1   peter   30  Delhi
2  sakshi   35   Pune

<b> Grouping </b>

In [46]:
df.groupby('City')['Age'].mean()

City
Chennai    25.0
Delhi      30.0
Pune       35.0
Name: Age, dtype: float64

In [47]:
df.groupby('City')['Age'].mean()

City
Chennai    25.0
Delhi      30.0
Pune       35.0
Name: Age, dtype: float64

<b> Merge </b>

In [48]:
data3= {'Name':['Sakshi','Amarsing','Chandwade'],
         'salary': [9000,50000,10000]}
df3 = pd.DataFrame (data3)
df3

        Name  salary
0     Sakshi    9000
1   Amarsing   50000
2  Chandwade   10000

In [49]:
pd.merge(df2,df3)

Empty DataFrame
Columns: [Name, Age, City, salary]
Index: []

In [41]:
pd.merge(df2,df3, on = 'Name')

        Name  salary_x  salary_y
0     Sakshi      2000      9000
1   Amarsing     50000     50000
2  Chandwade     10000     10000

# NUMPY

In [23]:
import numpy as np 
arr= np.array([1,2,3,4]);
print(arr)

[1 2 3 4]

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.zeros((2,3,))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((3,2,))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.numbers((1,2))

AttributeError: module 'numpy' has no attribute 'numbers'

## Manipulation

In [28]:
np.arange(6).reshape((2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
np.arange(12).reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
arr[:,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed